language: go
go: 1.13.x

before_install:
  - make install
  - go get golang.org/x/lint/golint
  - go get github.com/securego/gosec/cmd/gosec
  - go get github.com/fzipp/gocyclo

notifications:
  email: false

matrix:
  include:
    - stage: build
      script:
        - make vet
        - make lint
        - make security-check
        - make cyclo-check
        - make test

after_success:
  - make test-coverage
  - bash <(curl -s https://codecov.io/bash)
